version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@9.0.6
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo error simulation
      - ng build --prod
    finally:
      - echo this is the final building stage!
artifacts:
  base-directory: dist/my-angular-project
  files:
    - "**/*"
